name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  upload-download:
    runs-on: namespace-profile-default
    steps:
      - uses: actions/checkout@v4

      - run: env

      - uses: namespace-actions/upload-artifact@eaba85d205948ae47ac8325a4e3d0c2b2cd82fcf
        with:
          name: my-artifact
          path: README.md

      - uses: namespace-actions/download-artifact@1a4ed7285771998166564f09973317b91f384fce
        with:
          name: my-artifact
          path: dest

      - run: cat ./dest/README.md
