name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  upload-download:
    runs-on: namespace-profile-default
    steps:
      - uses: actions/checkout@v4

      - run: env

      - uses: namespace-actions/upload-artifact@15026750e13282d20e199b0fe71331fa589bd0e0
        with:
          name: my-artifact
          path: README.md

      - uses: namespace-actions/download-artifact@356a59845e417fd91d2dd09249693b993afdf8d2
        with:
          name: my-artifact
          path: dest

      - run: cat ./dest/README.md
