name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  on-nscloud-stable:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/5MB.zip

      - uses: namespace-actions/upload-artifact@v0
        with:
          name: 5mb
          path: 5MB.zip

      - uses: namespace-actions/download-artifact@v0
        with:
          name: 5mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  restore-job-nscloud-stable:
    runs-on: namespace-profile-default
    needs: on-nscloud-stable
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@v0
        with:
          name: 5mb
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      # Rerun using GUI button to test cross-attempt access.

  on-nscloud-head:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/5MB.zip

      - uses: namespace-actions/upload-artifact@HEAD
        with:
          name: 5mb-head
          path: 5MB.zip
          retention-days: 1

      - uses: namespace-actions/download-artifact@HEAD
        with:
          name: 5mb-head
          path: dest

      - name: Check
        run: |
          ls -la dest

  restore-job-nscloud-head:
    runs-on: namespace-profile-default
    needs: on-nscloud-head
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@HEAD
        with:
          name: 5mb-head
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      # Rerun using GUI button to test cross-attempt access.

  on-nscloud-old:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/5MB.zip

      - uses: namespace-actions/upload-artifact@v0.0.7
        with:
          name: 5mb
          path: 5MB.zip

      - uses: namespace-actions/download-artifact@v0.0.9
        with:
          name: 5mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  restore-job-nscloud-old:
    runs-on: namespace-profile-default
    needs: on-nscloud-old
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@v0.0.9
        with:
          name: 5mb
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      # Rerun using GUI button to test cross-attempt access.

  on-nscloud-v1:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/5MB.zip

      - uses: namespace-actions/upload-artifact@v1
        with:
          name: 5mb
          path: 5MB.zip

      - uses: namespace-actions/download-artifact@v1
        with:
          name: 5mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  restore-job-nscloud-v1:
    runs-on: namespace-profile-default
    needs: on-nscloud-v1
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@v0.0.9
        with:
          name: 5mb
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      # Rerun using GUI button to test cross-attempt access.

  on-github:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/5MB.zip

      - uses: actions/upload-artifact@v4
        with:
          name: 5mb
          path: 5MB.zip

      - uses: actions/download-artifact@v4
        with:
          name: 5mb
          path: dest

      - name: Check
        run: |
          ls -la dest
