name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  on-nscloud-stable:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: namespace-actions/upload-artifact@v0
        with:
          name: 200mb
          path: 200MB.zip

      - uses: namespace-actions/download-artifact@v0
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  on-nscloud-head:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: namespace-actions/upload-artifact@HEAD
        with:
          name: 200mb
          path: 200MB.zip
          retention-days: 1

      - uses: namespace-actions/download-artifact@HEAD
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  on-nscloud-v6:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: namespace-actions/upload-artifact@v0.0.7
        with:
          name: 200mb
          path: 200MB.zip

      - uses: namespace-actions/download-artifact@v0.0.7
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  on-github:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: actions/upload-artifact@v4
        with:
          name: 200mb
          path: 200MB.zip

      - uses: actions/download-artifact@v4
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  restore-job-nscloud-stable:
    runs-on: namespace-profile-default
    needs: on-nscloud-stable
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@v0
        with:
          name: 200mb
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      - name: Fail the job to test re-runs
        run:
          exit 1

  restore-job-nscloud-head:
    runs-on: namespace-profile-default
    needs: on-nscloud-head
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@HEAD
        with:
          name: 200mb
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      - name: Fail the job to test re-runs
        run:
          exit 1
