name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  on-nscloud:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: namespace-actions/upload-artifact@1a0a67e1ac808fbca3936ed9b6407ce393ca8f0c
        with:
          name: 200mb
          path: 200MB.zip

      - uses: namespace-actions/download-artifact@0667657d7a4d9cba5b1ff7095da00e8de2f0a3fc
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  on-github:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: actions/upload-artifact@v4
        with:
          name: 200mb
          path: 200MB.zip

      - uses: actions/download-artifact@v4
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  restore-job:
    runs-on: namespace-profile-default
    needs: on-nscloud
    steps:
      - name: Restore artifact from on-nscloud
        uses: namespace-actions/download-artifact@0667657d7a4d9cba5b1ff7095da00e8de2f0a3fc
        with:
          name: 200mb
          path: dest
      - name: Verify artifact
        run: |
          ls -l dest
      - name: Fail the job to test re-runs
        run:
          exit 1
