name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  on-nscloud:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: namespace-actions/upload-artifact@ffdc6a9808728fabe0d7a021233eb39395ecb354
        with:
          name: 200mb
          path: 200MB.zip

      - uses: namespace-actions/download-artifact@v0.0.1
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest

  on-github:
    runs-on: namespace-profile-default
    steps:
      - name: Download large file
        run: |
          wget http://ipv4.download.thinkbroadband.com/200MB.zip

      - uses: actions/upload-artifact@v4
        with:
          name: 200mb
          path: 200MB.zip

      - uses: actions/download-artifact@v4
        with:
          name: 200mb
          path: dest

      - name: Check
        run: |
          ls -la dest
