name: upload & download artifacts

on:
  push:
  workflow_dispatch:

jobs:
  upload-download:
    runs-on: namespace-profile-default
    steps:
      - uses: actions/checkout@v4

      - run: env

      - uses: namespace-actions/upload-artifact@1c4ce4a37dd6bdf7cc198f918931e3c8ef7dc379
        with:
          name: my-artifact
          path: README.md

      - uses: namespace-actions/download-artifact@ad0e2be8e12d80c17b907c42353fa5708ca64e50
        with:
          name: my-artifact
          path: dest

      - run: cat ./dest/README.md
